# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Delete_Null_Fields
                                 A QGIS plugin
 This plugin will delete all fields/columns from a vector layer or data which has all values equal to NULL.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-31
        copyright            : (C) 2019 by Abdullah / Mphil RS and GIS
        email                : spaciandd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Delete_Null_Fields class from file Delete_Null_Fields.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .delete_null_fields import Delete_Null_Fields
    return Delete_Null_Fields(iface)
